TOP=../..
include $(TOP)/configure/CONFIG

DB += aVac01.db
DB += aVac02.db
DB += aVac03.db
DB += asynIO.db
DB_INSTALLS += $(ASYN)/db/asynRecord.db
#DB_INSTALLS += $(TIME)/db/timestamp.db

include $(TOP)/configure/RULES
